/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyClock {}
  interface MyClockAttributes extends StencilHTMLAttributes {}

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface MyName {
    'name': string;
    'surname': string;
  }
  interface MyNameAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'surname'?: string;
  }

  interface MyWork {
    'enterprise': string;
    'job': string;
  }
  interface MyWorkAttributes extends StencilHTMLAttributes {
    'enterprise'?: string;
    'job'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyClock': Components.MyClock;
    'MyComponent': Components.MyComponent;
    'MyName': Components.MyName;
    'MyWork': Components.MyWork;
  }

  interface StencilIntrinsicElements {
    'my-clock': Components.MyClockAttributes;
    'my-component': Components.MyComponentAttributes;
    'my-name': Components.MyNameAttributes;
    'my-work': Components.MyWorkAttributes;
  }


  interface HTMLMyClockElement extends Components.MyClock, HTMLStencilElement {}
  var HTMLMyClockElement: {
    prototype: HTMLMyClockElement;
    new (): HTMLMyClockElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyNameElement extends Components.MyName, HTMLStencilElement {}
  var HTMLMyNameElement: {
    prototype: HTMLMyNameElement;
    new (): HTMLMyNameElement;
  };

  interface HTMLMyWorkElement extends Components.MyWork, HTMLStencilElement {}
  var HTMLMyWorkElement: {
    prototype: HTMLMyWorkElement;
    new (): HTMLMyWorkElement;
  };

  interface HTMLElementTagNameMap {
    'my-clock': HTMLMyClockElement
    'my-component': HTMLMyComponentElement
    'my-name': HTMLMyNameElement
    'my-work': HTMLMyWorkElement
  }

  interface ElementTagNameMap {
    'my-clock': HTMLMyClockElement;
    'my-component': HTMLMyComponentElement;
    'my-name': HTMLMyNameElement;
    'my-work': HTMLMyWorkElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
